import { BACKGROUND_NONE } from './backgrounds';
import {
  defaultCloseTabHotkey,
  defaultDeleteSessionHotkey,
  defaultNewSessionHotkey,
  defaultOpenTabHotkey,
  defaultTerminalHotkey,
  defaultWindowToggleHotkey,
} from './hotkeys';
import { DEFAULT_LOGO_ID } from './logos';
import { Settings } from './models';
import { DEFAULT_CUSTOM_THEME, DEFAULT_THEME_ID } from './themes';

/**
 * Settings used before the backend answers and as the base for drafts. Kept
 * free of Angular so tooling outside the app (e2e fixtures) can import it.
 */
export const FALLBACK_SETTINGS: Settings = {
  defaultSystemPrompt: '',
  securitySystemPromptEnabled: false,
  securitySystemPrompt: '',
  testingSystemPromptEnabled: false,
  testingSystemPrompt: '',
  architectureSystemPromptEnabled: false,
  architectureSystemPrompt: '',
  userSystemPrompts: [],
  modes: [],
  defaultModeId: 'coding',
  language: 'en',
  replyLanguage: null,
  theme: DEFAULT_THEME_ID,
  customTheme: { ...DEFAULT_CUSTOM_THEME },
  highContrast: false,
  extraFolders: [],
  settingsVersion: 3,
  openrouterBaseUrl: 'https://openrouter.ai/api/v1',
  providers: {},
  defaultModel: null,
  handoverModel: null,
  defaultReasoningEffort: 'medium',
  favoriteModels: [],
  providerByModel: {},
  autoCompactThreshold: 70,
  autoCompactMaxTokens: 150_000,
  maxToolIterations: 35,
  autoContinueAllSessions: false,
  subagentModel: null,
  compactionModel: null,
  titleModel: null,
  commitMessageModel: null,
  promptCaching: true,
  verifyBeforeFinish: true,
  commandRules: [],
  deniedCommandRules: [],
  allowedWebsites: [],
  deniedWebsites: [],
  mcpToolGrants: [],
  secretFolders: [],
  readFolders: [],
  pathFolders: [],
  permissionDefaults: { website: 'once', command: 'session', folder: 'session' },
  autoApproveReadOnly: true,
  autoApprovePackageScripts: true,
  autoApproveProjectExecutables: true,
  autoApproveProjectCommands: true,
  ignoreGitignored: true,
  scanGeneratedFiles: false,
  ignoreLocalDatabases: false,
  ignoreEnvFiles: true,
  fileIgnoreExemptions: [],
  fileIgnoreDisabled: [],
  fileIgnoreEnabled: [],
  fileIgnoreAdvanced: false,
  mcpAutoDiscovery: true,
  mcpFolders: [],
  mcpDisabled: [],
  mcpDisabledServers: [],
  mcpProgressiveDisclosure: true,
  skillsAutoDiscovery: true,
  skillFolders: [],
  skillsDisabled: [],
  skillsDisabledItems: [],
  marketplaceVerifiedOnly: true,
  keepAwake: true,
  tabsMultiline: true,
  pasteWordLimit: 500,
  openTabHotkey: defaultOpenTabHotkey(),
  closeTabHotkey: defaultCloseTabHotkey(),
  newSessionHotkey: defaultNewSessionHotkey(),
  deleteSessionHotkey: defaultDeleteSessionHotkey(),
  terminalHotkey: defaultTerminalHotkey(),
  hotkeys: {},
  windowToggleEnabled: false,
  windowToggleHotkey: defaultWindowToggleHotkey(),
  windowToggleAction: 'hide',
  windowToggleMaximize: false,
  zoom: 1,
  waitingChatsBanner: true,
  soundsEnabled: true,
  soundVolume: 0.6,
  doneSound: 'chime',
  permissionSound: 'ping',
  errorSound: 'alert',
  doneSoundPath: '',
  permissionSoundPath: '',
  errorSoundPath: '',
  background: BACKGROUND_NONE,
  backgroundImage: '',
  backgroundOpacity: 1,
  backgroundBlur: 0,
  glassOpacity: 1,
  logo: DEFAULT_LOGO_ID,
  sandbox: 'files',
  sandboxWritableFolders: [],
  sandboxUnreadableFolders: [],
  sandboxExcludedCommands: [],
  sandboxInlineCode: true,
  hooks: [],
  memoryEnabled: true,
  memorySuggestions: true,
  memories: [],
};
